name: Build and Test with JVM Flags
on: push
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        java-version: [22, 23-ea]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin
          
      - name: Cache Maven artifacts
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            
      # Cache node_modules
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: web-bundle/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/pom.xml', '**/package.json') }}
          restore-keys: |
            ${{ runner.os}}-node_modules-

      # Log the JVM flags to ensure documentation in logs
      - name: Log JVM Flags Used
        run: echo "Running tests with multiple JVM flags sets."

      # Measure Code Coverage with different flags (five variations)
      - name: Measure Code Coverage with Set 1
        run: |
          echo "Running with flags: -XX:+UseG1GC -XX:+PrintGCDetails"
          mvn -B clean test -DargLine="-XX:+UseG1GC -XX:+PrintGCDetails"
          mvn jacoco:report

      - name: Measure Code Coverage with Set 2
        run: |
          echo "Running with flags: -Xms512m -Xmx1024m"
          mvn -B clean test -DargLine="-Xms512m -Xmx1024m"
          mvn jacoco:report

      - name: Measure Code Coverage with Set 3
        run: |
          echo "Running with flags: -XX:+OptimizeStringConcat"
          mvn -B clean test -DargLine="-XX:+OptimizeStringConcat"
          mvn jacoco:report

      - name: Measure Code Coverage with Set 4
        run: |
          echo "Running with flags: -XX:+ShowCodeDetailsInExceptionMessages"
          mvn -B clean test -DargLine="-XX:+ShowCodeDetailsInExceptionMessages"
          mvn jacoco:report

      - name: Measure Code Coverage with Set 5
        run: |
          echo "Running with flags: -XX:+UseG1GC -Xmx2048m"
          mvn -B clean test -DargLine="-XX:+UseG1GC -Xmx2048m"
          mvn jacoco:report
